spring:
  datasource:
    username: flight_tracker
    password: flight_tracker
    url: jdbc:mysql://localhost:3306/flight_tracker
    
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true
    
    